
--Q17
select SBDEN, count(MACB) as "So chuyen bay den"
from CHUYENBAY
group by SBDEN
order by COUNT(MACB) ASC


--Q18
select SBDI, count(MACB) as "So chuyen bay di"
from CHUYENBAY
group by SBDI
order by COUNT(MACB) ASC

--Q19

select SBDI, NGAYDI, count(CB.MACB) AS "SO LUONG CHUYEN BAY"
from CHUYENBAY CB
JOIN LICHBAY LB ON CB.MACB = LB.MACB
GROUP BY SBDI, NGAYDI

--Q20
select SBDEN, NGAYDI, count(CB.MACB) AS "SO LUONG CHUYEN BAY"
from CHUYENBAY CB
JOIN LICHBAY LB ON CB.MACB = LB.MACB
GROUP BY SBDEN, NGAYDI

--Q21
SELECT LB.MACB, LB.NGAYDI, COUNT(PC.MANV) AS 'SO LUONG NHAN VIEN KHONG PHAI PHI CONG'
FROM LICHBAY LB
JOIN PHANCONG PC ON LB.MACB = PC.MACB AND LB.NGAYDI = PC.NGAYDI 
JOIN NHANVIEN NV ON PC.MANV = NV.MANV
WHERE NV.LOAINV = 0
GROUP BY LB.MACB, LB.NGAYDI


--Q22
SELECT CB.SBDI, COUNT(CB.MACB) AS 'SO LUONG CHUYEN BAY'
FROM CHUYENBAY CB
JOIN LICHBAY LB ON CB.MACB = LB.MACB
WHERE CB.SBDI = 'MIA' AND LB.NGAYDI = '2000-11-01'
GROUP BY CB.SBDI

--Q23
SELECT PC.MACB, PC.NGAYDI, COUNT(PC.MANV) AS 'SO LUONG NHAN VIEN'
FROM PHANCONG PC
GROUP BY PC.MACB, PC.NGAYDI
ORDER BY COUNT(PC.MANV) DESC

--Q24
SELECT MACB, NGAYDI, COUNT(MAKH) AS 'SO LUONG HANH KHACH'
FROM DATCHO
GROUP BY MACB, NGAYDI
ORDER BY COUNT(MAKH) DESC


--Q25
SELECT PC.MACB, PC.NGAYDI, SUM(NV.LUONG) AS 'TONG LUONG'
FROM PHANCONG PC
JOIN NHANVIEN NV ON PC.MANV = NV.MANV
GROUP BY PC.MACB, PC.NGAYDI
ORDER BY SUM(NV.LUONG) ASC

--Q26
SELECT AVG(NV.LUONG) AS 'LUONG TRUNG BINH'
FROM NHANVIEN NV
WHERE NV.LOAINV = 0

--Q27
SELECT AVG(LUONG) AS LUONG_TB
FROM NHANVIEN
WHERE LOAINV = 1

--Q28
SELECT LB.MALOAI, COUNT(LB.MACB) 'SO LUONG CHUYEN BAY'
FROM CHUYENBAY CB, LICHBAY LB
WHERE LB.MACB = CB.MACB AND CB.SBDEN = 'ORD'
GROUP BY LB.MALOAI

--Q29
SELECT SBDI, COUNT(CB.MACB) AS 'SO LUONG CHUYEN BAY'
FROM CHUYENBAY CB
WHERE CB.GIODI BETWEEN '10:00:00' AND '22:00:00'
GROUP BY CB.SBDI
HAVING COUNT(CB.MACB) > 2

--Q30
SELECT NV.TEN
FROM NHANVIEN NV
JOIN PHANCONG PC ON NV.MANV = PC.MANV
WHERE NV.LOAINV = '1'
GROUP BY NV.TEN, PC.NGAYDI
HAVING COUNT(PC.MACB) >= 2

--Q31
SELECT MACB, NGAYDI, COUNT(MAKH) AS SL_HK
FROM DATCHO 
GROUP BY MACB, NGAYDI
HAVING COUNT(MAKH) < 3

--Q32
SELECT LB.SOHIEU, LB.MALOAI
FROM PHANCONG PC
JOIN LICHBAY LB ON PC.MACB = LB.MACB AND PC.NGAYDI = LB.NGAYDI
WHERE PC.MANV = '1001' 
GROUP BY LB.SOHIEU, LB.MALOAI
HAVING COUNT(*) > 2

--Q33
SELECT HANGSX, COUNT(*) AS 'SO LUONG LOAI MAY BAY'
FROM LOAIMB
GROUP BY HANGSX