
use QLCB

--Q34
SELECT LMB.HANGSX, LB.SOHIEU, MB.MALOAI
FROM LICHBAY LB
JOIN MAYBAY MB ON LB.SOHIEU = MB.SOHIEU AND LB.MALOAI = MB.MALOAI
JOIN LOAIMB LMB ON MB.MALOAI = LMB.MALOAI
GROUP BY LB.SOHIEU, MB.MALOAI, LMB.HANGSX
HAVING COUNT(LB.MACB) >= ALL(
							SELECT COUNT(LB1.MACB)
							FROM LICHBAY LB1
							JOIN MAYBAY MB1 ON LB1.SOHIEU = MB1.SOHIEU AND LB1.MALOAI = MB1.MALOAI
							JOIN LOAIMB LMB1 ON MB1.MALOAI = LMB1.MALOAI
							GROUP BY LB1.SOHIEU, MB1.MALOAI, LMB1.HANGSX)

--Q35
SELECT NV.TEN AS 'TEN NHAN VIEN DUOC PHAN CONG NHIEU NHAT'
FROM NHANVIEN NV
JOIN PHANCONG PC ON PC.MANV = NV.MANV
WHERE NV.LOAINV = 0
GROUP BY NV.TEN
HAVING COUNT(PC.MANV) >= ALL(
							SELECT COUNT(PC1.MANV)
							FROM NHANVIEN NV1
							JOIN PHANCONG PC1 ON PC1.MANV = NV1.MANV
							WHERE NV1.LOAINV = 0
							GROUP BY NV1.TEN)

--Q36
SELECT NV.TEN AS "PHI CONG", NV.DCHI, NV.DTHOAI 
FROM NHANVIEN NV
JOIN PHANCONG PC ON NV.MANV = PC.MANV
WHERE NV.LOAINV = 1
GROUP BY NV.TEN, NV.DCHI, NV.DTHOAI 
HAVING COUNT(PC.MACB) >= ALL(
							SELECT COUNT(PC1.MACB) 
							FROM NHANVIEN NV1
							JOIN PHANCONG PC1 ON NV1.MANV = PC1.MANV
							WHERE NV1.LOAINV = 1
							GROUP BY NV1.TEN, NV1.DCHI, NV1.DTHOAI)

--Q37
SELECT CB.SBDEN, COUNT(CB.MACB) AS SL_CHUYENBAY 
FROM CHUYENBAY CB
GROUP BY CB.SBDEN 	
HAVING COUNT(CB.MACB) <= ALL(
							SELECT COUNT(CB1.MACB) 
							FROM CHUYENBAY CB1
							GROUP BY CB1.SBDEN)

--Q38
SELECT CB.SBDI, COUNT(CB.MACB) AS SL_CHUYENBAY 
FROM CHUYENBAY CB
GROUP BY CB.SBDI 	
HAVING COUNT(CB.MACB) >= ALL(
							SELECT COUNT(CB1.MACB) 
							FROM CHUYENBAY CB1
							GROUP BY CB1.SBDI)

--Q39
SELECT KH.TEN, KH.DCHI, KH.DTHOAI 
FROM KHACHHANG KH
JOIN DATCHO DC ON KH.MAKH = DC.MAKH
GROUP BY KH.TEN, KH.DCHI, KH.DTHOAI	
HAVING COUNT(DC.MACB) >= ALL(
							SELECT COUNT(DC1.MACB) 
							FROM KHACHHANG KH1
							JOIN DATCHO DC1 ON KH1.MAKH = DC1.MAKH
							GROUP BY KH1.TEN, KH1.DCHI, KH1.DTHOAI)

--Q40
SELECT NV.MANV, NV.TEN, NV.LUONG 
FROM NHANVIEN NV
JOIN KHANANG KN ON KN.MANV = NV.MANV
WHERE NV.LOAINV = 1
GROUP BY NV.MANV, NV.TEN, NV.LUONG 
HAVING COUNT(KN.MALOAI) >= ALL(
								SELECT COUNT(KN1.MALOAI)
								FROM NHANVIEN NV1
								JOIN KHANANG KN1 ON KN1.MANV = NV1.MANV
								WHERE NV1.LOAINV = 1
								GROUP BY NV1.MANV, NV1.TEN, NV1.LUONG)

--Q41
SELECT NV.MANV, NV.TEN, NV.LUONG 
FROM NHANVIEN NV
WHERE NV.LOAINV = 0 AND NV.LUONG >= ALL(
										SELECT NV1.LUONG 
										FROM NHANVIEN NV1
										WHERE NV1.LOAINV = 0)

--Q42

--Q43
SELECT CB.MACB, CB.GIODI, CB.GIODEN
FROM CHUYENBAY CB 
WHERE CB.GIODI <= ALL(
					SELECT CB1.GIODI						
					FROM CHUYENBAY CB1)

--Q44
SELECT CB.MACB, DATEDIFF(MINUTE,CB.GIODI,CB.GIODEN) AS 'THOI GIAN BAY'
FROM CHUYENBAY CB
WHERE DATEDIFF(MINUTE, CB.GIODI, CB.GIODEN) >= ALL(
													SELECT DATEDIFF(MINUTE, CB1.GIODI, CB1.GIODEN)
													FROM CHUYENBAY CB1)

--Q45
SELECT CB.MACB, DATEDIFF(MINUTE,CB.GIODI,CB.GIODEN) AS 'THOI GIAN BAY'
FROM CHUYENBAY CB
WHERE DATEDIFF(MINUTE, CB.GIODI, CB.GIODEN) <= ALL(
													SELECT DATEDIFF(MINUTE, CB1.GIODI, CB1.GIODEN)
													FROM CHUYENBAY CB1)

--Q46
SELECT LB.MACB, LB.NGAYDI 
FROM LICHBAY LB
WHERE LB.MALOAI = 'B747'
GROUP BY LB.MACB, LB.NGAYDI 
HAVING COUNT(*) >= ALL(
						SELECT COUNT(*) 
						FROM LICHBAY LB1
						WHERE LB1.MALOAI = 'B747'
						GROUP BY LB1.MACB, LB1.NGAYDI)

--Q47
SELECT PC.MACB, COUNT(PC.MANV) AS 'SO LUONG NHAN VIEN'
FROM PHANCONG PC
JOIN NHANVIEN NV ON PC.MANV = NV.MANV
JOIN LICHBAY LB ON PC.MACB = LB.MACB
JOIN DATCHO DC ON DC.MACB = LB.MACB
WHERE NV.LOAINV = 0
GROUP BY PC.MACB
HAVING COUNT(DC.MAKH) >= 3

--Q48
SELECT NV.LOAINV, COUNT(NV.MANV) AS 'SO LUONG NHAN VIEN'
FROM NHANVIEN NV
GROUP BY NV.LOAINV
HAVING SUM(NV.LUONG) > 600000

--Q49
SELECT DC.MACB, (SELECT COUNT(DC1.MAKH) FROM DATCHO DC1 WHERE DC.MACB = DC1.MACB) AS 'SO LUONG KHACH HANG'
FROM DATCHO DC
JOIN PHANCONG PC ON DC.MACB = PC.MACB
GROUP BY DC.MACB
HAVING COUNT(PC.MANV) >= 3

--Q50
SELECT DISTINCT MB.MALOAI, (SELECT COUNT(MB1.SOHIEU) FROM MAYBAY MB1 WHERE MB1.MALOAI = MB.MALOAI) AS 'SO LUONG CHUYEN BAY'
FROM MAYBAY MB
JOIN LICHBAY LB ON  MB.MALOAI = LB.MALOAI
GROUP BY MB.MALOAI
HAVING COUNT(MB.SOHIEU) > 1
