

--Q51

--EXCEPT
SELECT DISTINCT LB.MACB
FROM LOAIMB LMB
JOIN LICHBAY LB ON LB.MALOAI = LMB.MALOAI
WHERE NOT EXISTS(
				SELECT MALOAI
				FROM LOAIMB LMB1
				WHERE LMB1.HANGSX = 'Boeing'
				EXCEPT
				SELECT LMB1.MALOAI
				FROM LICHBAY LMB1
				WHERE LMB1.MALOAI = LMB.MALOAI)




--Q52
--NOT EXISTS
SELECT NV.MANV, NV.TEN
FROM NHANVIEN NV
WHERE NV.LOAINV = 1 AND NOT EXISTS(
	SELECT LMB.MALOAI
	FROM LOAIMB LMB
	WHERE LMB.HANGSX = 'Airbus' AND NOT EXISTS(
		SELECT KN.MALOAI
		FROM KHANANG KN
		WHERE KN.MANV = NV.MANV AND KN.MALOAI = LMB.MALOAI))






--Q53
--COUNT
SELECT NV.TEN
FROM NHANVIEN NV
JOIN PHANCONG PC ON PC.MANV = NV.MANV
JOIN LICHBAY LB ON PC.NGAYDI = LB.NGAYDI AND PC.MACB = LB.MACB
WHERE NV.LOAINV = 0 AND LB.MACB = '100'
GROUP BY NV.MANV, NV.TEN
HAVING COUNT(*) = (SELECT COUNT(*)
FROM LICHBAY LB1 WHERE LB1.MACB = 100)






--Q54
--EXCEPT
SELECT DISTINCT LB.NGAYDI
FROM LICHBAY LB
WHERE NOT EXISTS(
				SELECT LMB.MALOAI
				FROM  LOAIMB LMB
				WHERE LMB.HANGSX = 'Boeing'
				EXCEPT
				SELECT LB1.MALOAI
				FROM LICHBAY LB1
				WHERE LB1.NGAYDI = LB.NGAYDI)





--Q55
--COUNT
SELECT LMB.MALOAI 
FROM LOAIMB LMB
JOIN LICHBAY LB ON LMB.MALOAI=LB.MALOAI
WHERE LMB.HANGSX = 'Boeing' 
GROUP BY LMB.MALOAI
HAVING COUNT(DISTINCT LB.NGAYDI) =(
									SELECT COUNT(DISTINCT LB1.NGAYDI) 
									FROM LICHBAY LB1)



--Q56
--NOT EXISTS
SELECT KH.MAKH, KH.TEN
FROM KHACHHANG KH
WHERE NOT EXISTS(
	SELECT LB.NGAYDI
	FROM LICHBAY LB
	WHERE LB.NGAYDI BETWEEN '10/31/2000' AND '11/1/2000' AND NOT EXISTS(
		SELECT DC.MAKH
		FROM DATCHO DC
		WHERE DC.MAKH =KH.MAKH AND DC.NGAYDI = LB.NGAYDI))




--Q58
--COUNT
SELECT CB.SBDI
FROM CHUYENBAY CB
JOIN LICHBAY LB ON LB.MACB = CB.MACB
JOIN LOAIMB LMB ON LMB.MALOAI = LB.MALOAI
WHERE LMB.HANGSX = 'Boeing'
GROUP BY CB.SBDI
HAVING COUNT(DISTINCT LMB.MALOAI) = (
	SELECT COUNT(DISTINCT LMB1.MALOAI)
	FROM LOAIMB LMB1
	WHERE LMB1.HANGSX = 'Boeing')