
--Q58

--EXCEPT
SELECT DISTINCT GV1.HOTEN
FROM GIAOVIEN GV1
WHERE NOT EXISTS(
				(SELECT CD1.MACD FROM CHUDE CD1)
				EXCEPT
				(SELECT CD2.MACD 
				FROM THAMGIADT TGDT
				JOIN DETAI DT ON TGDT.MADT = DT.MADT
				JOIN CHUDE CD2 ON CD2.MACD = DT.MACD
				WHERE TGDT.MAGV = GV1.MAGV)
				)

--NOT EXISTS
SELECT DISTINCT GV1.HOTEN
FROM GIAOVIEN GV1
WHERE NOT EXISTS(
	SELECT * 
	FROM CHUDE CD1
	WHERE NOT EXISTS(
		SELECT * 
		FROM THAMGIADT TGDT1
		JOIN DETAI DT1 ON TGDT1.MADT = DT1.MADT
		WHERE DT1.MACD = CD1.MACD AND TGDT1.MAGV = GV1.MAGV))


--COUNT
SELECT GV.HOTEN
FROM GIAOVIEN GV
JOIN THAMGIADT TGDT ON TGDT.MAGV = GV.MAGV
JOIN DETAI DT ON TGDT.MADT = DT.MADT
JOIN CHUDE CD ON DT.MACD = CD.MACD
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT CD.MACD) = (SELECT COUNT(*) FROM CHUDE)




--Q59
--EXCEPT
SELECT DISTINCT DT1.MADT, DT1.TENDT 
FROM DETAI DT1
JOIN THAMGIADT TGDT1 ON DT1.MADT = TGDT1.MADT
WHERE NOT EXISTS(
				SELECT GV.MAGV
				FROM GIAOVIEN GV
				WHERE GV.MABM = 'HTTT'
				EXCEPT
				SELECT GV2.MAGV 
				FROM GIAOVIEN GV2
				JOIN THAMGIADT TGDT2 ON GV2.MAGV = TGDT2.MAGV
				WHERE TGDT1.MADT = TGDT2.MADT)


--NOT EXISTS
SELECT DISTINCT DT1.MADT, DT1.TENDT 
FROM DETAI DT1
JOIN THAMGIADT TGDT1 ON DT1.MADT = TGDT1.MADT
AND NOT EXISTS(
               SELECT * 
			   FROM GIAOVIEN GV
			   WHERE GV.MABM = 'HTTT'
			   AND NOT EXISTS (
							   SELECT *
							   FROM THAMGIADT TGDT2
							   WHERE TGDT2.MADT = TGDT1.MADT AND GV.MAGV = TGDT2.MAGV))
			   
--Q60
--EXCEPT

SELECT DISTINCT DT.MADT, DT.TENDT 
FROM DETAI DT
JOIN THAMGIADT TGDT1 ON DT.MADT = TGDT1.MADT
WHERE NOT EXISTS(
				SELECT GV.MAGV
				FROM GIAOVIEN GV
				JOIN BOMON BM ON GV.MABM = BM.MABM
				WHERE BM.TENBM = N'Hệ thống thông tin'   
                EXCEPT 
				SELECT TGDT2.MAGV 
				FROM THAMGIADT TGDT2
				WHERE TGDT1.MADT = TGDT2.MADT)

--NOT EXISTS
SELECT DISTINCT DT1.MADT, DT1.TENDT 
FROM DETAI DT1
JOIN THAMGIADT TGDT1 ON DT1.MADT = TGDT1.MADT
AND NOT EXISTS(
               SELECT * 
			   FROM GIAOVIEN GV
			   JOIN BOMON BM ON GV.MABM = BM.MABM
			   WHERE BM.TENBM = N'Hệ thống thông tin'
			   AND NOT EXISTS (
							   SELECT *
							   FROM THAMGIADT TGDT2
							   WHERE TGDT2.MADT = TGDT1.MADT AND GV.MAGV = TGDT2.MAGV))


--Q61
SELECT DISTINCT GV.MAGV, GV.HOTEN
FROM THAMGIADT TGDT1
JOIN GIAOVIEN GV ON TGDT1.MAGV = GV.MAGV
WHERE NOT EXISTS(
				SELECT DT.MADT
				FROM DETAI DT
				WHERE DT.MACD = 'QLGD'
				EXCEPT
				SELECT TGDT2.MADT
				FROM THAMGIADT TGDT2 
				WHERE TGDT2.MAGV = TGDT1.MAGV)
			   
--Q62
SELECT DISTINCT GV.MAGV, GV.HOTEN 
FROM THAMGIADT TGDT1
JOIN GIAOVIEN GV ON TGDT1.MAGV = GV.MAGV
WHERE GV.HOTEN <> N'Trần Trà Hương' AND NOT EXISTS(
													SELECT DT.MADT 
													FROM DETAI DT
													JOIN THAMGIADT TGDT2 ON TGDT2.MADT = DT.MADT
													JOIN GIAOVIEN GV2 ON TGDT2.MAGV = GV2.MAGV
													WHERE GV2.HOTEN = N'Trần Trà Hương'
													EXCEPT
													SELECT TGDT3.MADT 
													FROM THAMGIADT TGDT3
													WHERE TGDT3.MAGV = TGDT1.MAGV)

--Q63
SELECT DISTINCT DT.MADT, DT.TENDT 
FROM DETAI DT
JOIN THAMGIADT TGDT1 ON TGDT1.MADT = DT.MADT
WHERE NOT EXISTS(
				SELECT gv.MAGV 
				FROM GIAOVIEN GV 
				JOIN BOMON BM ON GV.MABM = BM.MABM 
				WHERE BM.TENBM = N'Hóa Hữu Cơ'
				EXCEPT 
				SELECT TGDT2.MAGV
				FROM THAMGIADT TGDT2 
				WHERE TGDT2.MADT = TGDT1.MADT)

--Q64
SELECT DISTINCT GV.MAGV, GV.HOTEN 
FROM THAMGIADT TGDT1
JOIN GIAOVIEN GV ON TGDT1.MAGV = GV.MAGV
WHERE NOT EXISTS(
				SELECT MADT FROM CONGVIEC 
				WHERE MADT = '006'
				EXCEPT
				SELECT TGDT2.MADT
				FROM THAMGIADT TGDT2
				WHERE TGDT2.MAGV = TGDT1.MAGV)

--Q65
SELECT DISTINCT GV.MAGV, GV.HOTEN 
FROM THAMGIADT TGDT1
JOIN GIAOVIEN GV ON TGDT1.MAGV = GV.MAGV
WHERE NOT EXISTS(
				SELECT DT.MADT 
				FROM DETAI DT
				JOIN CHUDE CD ON DT.MACD = CD.MACD 
				WHERE CD.TENCD = N'Ứng dụng công nghệ'
				EXCEPT
				SELECT TGDT2.MADT 
				FROM THAMGIADT TGDT2 
				WHERE TGDT2.MAGV = TGDT1.MAGV)

--Q66
SELECT DISTINCT GV.MAGV, GV.HOTEN 
FROM THAMGIADT TGDT1
JOIN GIAOVIEN GV ON TGDT1.MAGV = GV.MAGV 
WHERE NOT EXISTS(
				SELECT DT.MADT 
				FROM DETAI DT
				JOIN GIAOVIEN GV2 ON DT.GVCNDT = GV2.MAGV
				WHERE GV2.HOTEN = N'Trần Trà Hương'
				EXCEPT
				SELECT TGDT2.MADT 
				FROM THAMGIADT TGDT2
				WHERE TGDT2.MAGV = TGDT1.MAGV)

--Q67
SELECT DISTINCT DT.MADT, DT.TENDT 
FROM DETAI DT
JOIN THAMGIADT TGDT1 ON DT.MADT = TGDT1.MADT
WHERE NOT EXISTS(
				SELECT GV.MAGV 
				FROM GIAOVIEN GV
				JOIN BOMON BM ON GV.MABM = BM.MABM
				WHERE BM.MAKHOA = 'CNTT'
				EXCEPT
				SELECT TGDT2.MAGV
				FROM THAMGIADT TGDT2
				WHERE TGDT1.MADT = TGDT2.MADT)

--Q68
SELECT DISTINCT GV.MAGV, GV.HOTEN 
FROM THAMGIADT TGDT1
JOIN GIAOVIEN GV ON TGDT1.MAGV = GV.MAGV
WHERE NOT EXISTS(
				SELECT CV1.MADT 
				FROM CONGVIEC CV1
				JOIN DETAI DT ON CV1.MADT = DT.MADT
				WHERE DT.TENDT = N'Nghiên cứu tế bào gốc'
				EXCEPT
				SELECT TGDT2.MADT 
				FROM THAMGIADT TGDT2
				JOIN CONGVIEC CV2 ON TGDT2.MADT = CV2.MADT AND TGDT2.STT = CV2.SOTT
				WHERE TGDT2.MAGV = TGDT1.MAGV)

--Q69
SELECT DISTINCT GV.MAGV, GV.HOTEN 
FROM THAMGIADT TGDT1
JOIN GIAOVIEN GV ON TGDT1.MAGV = GV.MAGV
WHERE NOT EXISTS(
				SELECT DT.MADT 
				FROM DETAI DT
				WHERE DT.KINHPHI > 10000000
				EXCEPT
				SELECT TGDT2.MADT 
				FROM THAMGIADT TGDT2 
				WHERE TGDT2.MAGV = TGDT1.MAGV)

--Q70

SELECT DISTINCT DT.MADT, DT.TENDT 
FROM DETAI DT
JOIN THAMGIADT TGDT1 ON DT.MADT = TGDT1.MADT
WHERE NOT EXISTS(
				SELECT GV.MAGV 
				FROM GIAOVIEN GV
				JOIN BOMON BM ON GV.MABM = BM.MABM
				JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
				WHERE K.TENKHOA = N'Sinh học'
				EXCEPT 
				SELECT TGDT2.MAGV 
				FROM THAMGIADT TGDT2 
				WHERE TGDT2.MADT = TGDT2.MADT)

--Q71
SELECT DISTINCT GV.MAGV, GV.HOTEN, GV.NGSINH
FROM THAMGIADT TGDT1
JOIN GIAOVIEN GV ON TGDT1.MAGV = GV.MAGV
WHERE NOT EXISTS(
				SELECT CV1.MADT 
				FROM CONGVIEC CV1
				JOIN DETAI DT ON CV1.MADT = DT.MADT
				WHERE DT.TENDT = N'Ứng dụng hóa học xanh'
				EXCEPT
				SELECT TGDT2.MADT 
				FROM THAMGIADT TGDT2
				JOIN CONGVIEC CV2 ON TGDT2.MADT = CV2.MADT AND TGDT2.STT = CV2.SOTT
				WHERE TGDT2.MAGV = TGDT1.MAGV)


--Q72
SELECT DISTINCT GV.MAGV, GV.HOTEN, BM.TENBM, GV.GVQLCM
FROM THAMGIADT TGDT1
JOIN GIAOVIEN GV ON TGDT1.MAGV = GV.MAGV
JOIN BOMON BM ON GV.MAGV = BM.MABM
WHERE NOT EXISTS(
				SELECT DT.MADT 
				FROM DETAI DT
				JOIN CHUDE CD ON DT.MACD = CD.MACD 
				WHERE CD.TENCD = N'Nghiên cứu phát triển'
				EXCEPT
				SELECT TGDT2.MADT 
				FROM THAMGIADT TGDT2 
				WHERE TGDT2.MAGV = TGDT1.MAGV)