
use QLGV

--q35
SELECT distinct  LUONG as "Luong cao nhat"
FROM GIAOVIEN
WHERE LUONG >=ALL(SELECT LUONG FROM GIAOVIEN)

--q36
SELECT *
FROM GIAOVIEN
WHERE LUONG >=ALL(SELECT LUONG FROM GIAOVIEN)

--q37
SELECT *
FROM GIAOVIEN
WHERE  MABM = 'HTTT' and LUONG >= ALL(
SELECT LUONG 
FROM GIAOVIEN
WHERE MABM = 'HTTT')

--q38
SELECT HOTEN AS 'GIÁO VIÊN LỚN TUỔI NHẤT'
FROM GIAOVIEN GV
JOIN BOMON BM ON GV.MABM = BM.MABM
WHERE BM.TENBM = N'Hệ thống thông tin' and YEAR(NGSINH) <= ALL(
SELECT YEAR(NGSINH)
FROM GIAOVIEN GV
JOIN BOMON BM ON GV.MABM = BM.MABM
WHERE BM.TENBM = N'Hệ thống thông tin' 
)

--Q40
SELECT GV.HOTEN, GV.LUONG, K.TENKHOA
FROM GIAOVIEN GV
JOIN BOMON BM ON GV.MABM = BM.MABM
JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
WHERE GV.LUONG >=ALL(
SELECT GV2.LUONG 
FROM GIAOVIEN GV2)

--Q41
SELECT *
FROM GIAOVIEN GV1
WHERE GV1.LUONG >= ALL(
SELECT GV2.LUONG
FROM GIAOVIEN GV2 
WHERE GV1.MABM = GV2.MABM 
)

--Q42
SELECT DT.TENDT
FROM DETAI DT
WHERE DT.MADT NOT IN (
SELECT DISTINCT TGDT.MADT
FROM GIAOVIEN GV
JOIN THAMGIADT TGDT ON GV.MAGV = TGDT.MAGV 
WHERE gv.HOTEN = N'Nguyễn Hoài An')

--Q43
SELECT DT.TENDT, (SELECT GV1.HOTEN FROM GIAOVIEN GV1 WHERE GV1.MAGV = DT.GVCNDT) AS 'GIÁO VIÊN CHỦ NHIỆM ĐỀ TÀI'
FROM DETAI DT
WHERE DT.MADT NOT IN (
SELECT DISTINCT TGDT.MADT
FROM GIAOVIEN GV
JOIN THAMGIADT TGDT ON GV.MAGV = TGDT.MAGV 
WHERE gv.HOTEN = N'Nguyễn Hoài An')

--Q44
SELECT GV.HOTEN
FROM GIAOVIEN GV 
JOIN BOMON BM ON GV.MABM = BM.MABM
WHERE BM.MAKHOA = 'CNTT' AND NOT EXISTS(
SELECT *
FROM THAMGIADT TGDT
WHERE GV.MAGV = TGDT.MAGV 
)

--Q45
SELECT *
FROM GIAOVIEN GV
WHERE NOT EXISTS(
SELECT *
FROM THAMGIADT TGDT
WHERE TGDT.MAGV = GV.MAGV
)

--Q46
SELECT *
FROM GIAOVIEN GV1
WHERE GV1.LUONG > (SELECT GV2.LUONG
FROM GIAOVIEN GV2
WHERE GV2.HOTEN = N'Nguyễn Hoài An'
)

--Q47
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV
JOIN BOMON BM ON GV.MABM = BM.MABM
JOIN THAMGIADT TGDT ON TGDT.MAGV = GV.MAGV
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT TGDT.MAGV)>=1

--Q48
SELECT *
FROM GIAOVIEN GV1
WHERE EXISTS (SELECT *
			  FROM GIAOVIEN GV2
			  WHERE GV1.MAGV <> GV2.MAGV AND GV1.HOTEN = GV2.HOTEN AND GV1.PHAI = GV2.PHAI AND GV1.MABM = GV2.MABM)

--Q49
SELECT * 
FROM GIAOVIEN GV1
WHERE GV1.LUONG > ANY(
						SELECT GV2.LUONG 
						FROM GIAOVIEN GV2
						JOIN BOMON BM ON GV2.MABM = BM.MABM
						WHERE BM.TENBM = N'Công nghệ tri thức'
					 )

--Q50
SELECT * 
FROM GIAOVIEN GV1
WHERE GV1.LUONG > ALL (
						SELECT GV2.LUONG 
						FROM GIAOVIEN GV2
						JOIN BOMON BM on GV2.MABM = BM.MABM
						WHERE BM.TENBM = N'Hệ thống thông tin')

--Q52
SELECT GV1.HOTEN
FROM GIAOVIEN GV1
JOIN DETAI DT1 ON DT1.GVCNDT = GV1.MAGV
GROUP BY GV1.HOTEN  
HAVING COUNT(*) >= ALL(
						SELECT COUNT(*)
						FROM DETAI DT2,GIAOVIEN GV2
						WHERE DT2.GVCNDT = GV2.MAGV
						GROUP BY GV2.HOTEN)   

--Q53
SELECT GV1.MABM
FROM GIAOVIEN GV1
GROUP BY MABM
HAVING COUNT(*) >= ALL(
						SELECT COUNT(*)
						FROM GIAOVIEN GV2
						GROUP BY GV2.MABM)

--Q54
SELECT GV1.HOTEN, BM.TENBM 
FROM GIAOVIEN GV1
JOIN THAMGIADT TGDT1 ON TGDT1.MAGV= GV1.MAGV
JOIN BOMON BM ON GV1.MABM = BM.MABM
GROUP BY GV1.HOTEN, BM.TENBM  
HAVING COUNT(*) >= ALL(
						SELECT COUNT(*)
						FROM THAMGIADT TGDT2
						JOIN GIAOVIEN GV2 ON TGDT2.MAGV= GV2.MAGV
						GROUP BY GV2.HOTEN)

--Q55
SELECT GV1.HOTEN 
FROM GIAOVIEN GV1
JOIN THAMGIADT TGDT1 ON GV1.MAGV = TGDT1.MAGV
WHERE GV1.MABM = 'HTTT' 
GROUP BY GV1.HOTEN  
HAVING COUNT(*) >= ALL(
						SELECT COUNT(*)
						FROM THAMGIADT TGDT2
						JOIN GIAOVIEN GV2 ON TGDT2.MAGV = GV2.MAGV 
						WHERE GV2.MABM = 'HTTT' 
						GROUP BY GV2.HOTEN)
--Q56
SELECT GV1.HOTEN, BM.TENBM 
FROM GIAOVIEN GV1
JOIN NGUOITHAN NT1 ON GV1.MAGV = NT1.MAGV
JOIN BOMON BM ON BM.MABM = GV1.MABM
GROUP BY GV1.HOTEN, BM.TENBM  
HAVING COUNT(*) >= ALL(
						SELECT COUNT(*)
						FROM NGUOITHAN NT2,GIAOVIEN GV2
						WHERE NT2.MAGV = GV2.MAGV  
						GROUP BY GV2.HOTEN)

--Q57
SELECT GV1.HOTEN
FROM GIAOVIEN GV1
JOIN DETAI DT1 ON GV1.MAGV = DT1.GVCNDT
JOIN BOMON BM1 ON GV1.MAGV =BM1.TRUONGBM
GROUP BY GV1.HOTEN  
HAVING COUNT(*) >= ALL(
						SELECT COUNT(*)
						FROM GIAOVIEN GV2 
						JOIN DETAI DT2 ON GV2.MAGV = DT2.GVCNDT
						JOIN BOMON BM2 ON GV2.MAGV =BM2.TRUONGBM
						GROUP BY GV2.HOTEN) 
